name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Run linter
        run: |
          poetry run ruff check .
      - name: Run tests
        env:
          PYTHONPATH: .
        run: |
          poetry run pytest --maxfail=1 --disable-warnings -q